# Generated by Django 5.2.1 on 2025-05-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
