# Generated by Django 5.2.1 on 2025-06-05 17:18

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcaldiaVistas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=100)),
                ('alcaldia', models.CharField(db_column='Alcaldia', max_length=100)),
                ('colonia', models.CharField(db_column='Colonia', max_length=100)),
                ('promedio_mxn', models.CharField(db_column='Promedio_MXN', max_length=30)),
                ('zona', models.CharField(blank=True, db_column='Zona', max_length=50, null=True)),
            ],
            options={
                'db_table': 'alcaldia_vistas',
                'managed': True,  # ← CAMBIADO
            },
        ),
        migrations.CreateModel(
            name='CodigosPostales',
            fields=[
                ('id_codigo_postal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'codigos_postales',
                'managed': True,  # ← CAMBIADO
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': True,  # ← CAMBIADO
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'municipios',
                'managed': True,  # ← CAMBIADO
            },
        ),
        migrations.CreateModel(
            name='Colonias',
            fields=[
                ('id_colonia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('promedio_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_municipio', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.municipios')),
            ],
            options={
                'db_table': 'colonias',
                'managed': True,
                'unique_together': {('nombre', 'id_municipio')},
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_propiedad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=100)),
                ('recamaras', models.IntegerField()),
                ('sanitarios', models.DecimalField(decimal_places=1, max_digits=3)),
                ('estacionamiento', models.IntegerField()),
                ('terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('construccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_conservacion', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('valor_aprox', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_judicial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_comercial', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_codigo_postal', models.ForeignKey(db_column='id_codigo_postal', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.codigospostales')),
                ('id_colonia', models.ForeignKey(blank=True, db_column='id_colonia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.colonias')),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.estados')),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.municipios')),
            ],
            options={
                'db_table': 'propiedades',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
        migrations.DeleteModel(
            name='AlcaldiaVista',
        ),
    ]
