# Generated by Django 5.2.1 on 2025-06-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alcaldiavistas_codigospostales_estados_municipios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficaAlcaldia',
            fields=[
                ('id_grafica', models.AutoField(primary_key=True, serialize=False)),
                ('grafica_alcaldia', models.CharField(max_length=100, null=True)),
                ('grafica_nombre', models.CharField(max_length=100, null=True)),
                ('grafica_cp', models.IntegerField(null=True)),
                ('grafica_prom_prop', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grafica_prom_hey', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grafica_prom_clau', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grafica_prom_mud', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grafica_prom_altal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grafica_promedio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'graficas_alcaldias',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(default='12345678', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('roles', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='codigospostales',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='colonias',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.estados'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='valor_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
