# Generated by Django 5.2.1 on 2025-06-29 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_graficaalcaldia_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alcaldiavistas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='graficaalcaldia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='municipios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='codigospostales',
            name='id_colonia',
            field=models.ForeignKey(db_column='id_colonia', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.colonias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigospostales',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.estados'),
        ),
        migrations.AddField(
            model_name='codigospostales',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.municipios'),
        ),
        migrations.AlterUniqueTogether(
            name='codigospostales',
            unique_together={('codigo', 'id_colonia')},
        ),
    ]
