# Generated by Django 5.2.1 on 2025-06-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_alcaldiavistas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.estados'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='municipios',
            unique_together={('nombre', 'id_estado')},
        ),
    ]
